workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.menderesucar.calis360

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean iOS pods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release --export-method=app-store
    artifacts:
      - build/ios/ipa/*.ipa
