// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvKQ-4wUzRnRL_BiLSLCovSMhiOrNJS0',
    appId: '1:373433533689:web:3916eb875cca1706f0ce28',
    messagingSenderId: '373433533689',
    projectId: 'zirve-eac97',
    authDomain: 'zirve-eac97.firebaseapp.com',
    storageBucket: 'zirve-eac97.firebasestorage.app',
    measurementId: 'G-7E64Q97PT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuh13ySz4AXGrxWN1AGDHF0dhBPtBqPQ',
    appId: '1:373433533689:android:d80683e9bc19f27af0ce28',
    messagingSenderId: '373433533689',
    projectId: 'zirve-eac97',
    storageBucket: 'zirve-eac97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOvKQ-4wUzRnRL_BiLSLCovSMhiOrNJS0',
    appId: '1:373433533689:web:1ae8aff3741015b5f0ce28',
    messagingSenderId: '373433533689',
    projectId: 'zirve-eac97',
    authDomain: 'zirve-eac97.firebaseapp.com',
    storageBucket: 'zirve-eac97.firebasestorage.app',
    measurementId: 'G-5GJN8ZEYQQ',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMPoIdNuV4o8nS20kVs1idFFwf15L6f5c',
    appId: '1:373433533689:ios:e537905c994b8875f0ce28',
    messagingSenderId: '373433533689',
    projectId: 'zirve-eac97',
    storageBucket: 'zirve-eac97.firebasestorage.app',
    iosBundleId: 'com.calis360.zirve',
  );
}
